apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servox.fullname" . }}
  namespace: {{ include "servox.namespace" . }}
  labels:
    {{- include "servox.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "servox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "servox.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "servox.fullname" . }}
      containers:
      - name: servo
        image: {{ include "servox.servoImage" . }}
        terminationMessagePolicy: FallbackToLogsOnError
        args:
          - 'run'
          - '--check'
        env:
{{- if eq .Values.connectionSettingsType "static" }}
        - name: APPD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "servox.fullname" . }}
              key: client_secret
{{- end }}
        - name: SERVO_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: {{ include "servox.fullname" . }}
              key: log_level
        - name: POD_NAME
          valueFrom:
              fieldRef:
                fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
        - name: servo-config-volume
          mountPath: /servo/servo.yaml
          subPath: servo.yaml
          readOnly: true
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
      volumes:
      - name: servo-config-volume
        configMap:
          name: {{ include "servox.fullname" . }}
          items:
          - key: servo.yaml
            path: servo.yaml

      # Prefer deployment onto a Node labeled role=servo
      # This ensures physical isolation and network transport if possible
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node.opsani.com/role
                operator: In
                values:
                - servo
