{{- if .Values.clientSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servox.fullname" . }}
  labels:
    {{- include "servox.labels" . | nindent 4 }}
type: Opaque
stringData:
  client_secret: {{ .Values.clientSecret }}
{{- end -}}
