{{- if eq .Values.connectionSettingsType "static" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servox.fullname" . }}
  namespace: {{ include "servox.namespace" . }}
  labels:
    {{- include "servox.labels" . | nindent 4 }}
type: Opaque
stringData:
  client_secret: {{ .Values.clientSecret | required ".Values.clientSecret is required with static connection settings type" }}
{{- end -}}
